ALTER TABLE users
    ADD COLUMN IF NOT EXISTS workplace TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS employee_number TEXT NOT NULL DEFAULT '';
